### ISSUE TITLE
Take filenames as track names if the files lack tags

### ISSUE THREAD

**Issue by dikonov** [dakeryas/deadbeef-dr-meter#1]
Please, write the file names and track numbers in the output after the calculated DR values instead of  "00-(null)" if no tags are defined. Some file formats (wav, dts, au) do not suppott tagging.  

The header could use the album dir name instead of  (null) / (null) too.

This output is rather cryptic.
```
Analysed: (null) / (null)
---------------------------------------------------------------------------------------------------------
DR     Peak        RMS         Duration  Track
---------------------------------------------------------------------------------------------------------
DR12   -1.19 dB    -16.00 dB       4:07  00-(null)
DR13    0.00 dB    -17.23 dB       4:28  00-(null)
DR13   -2.04 dB    -17.42 dB       3:34  00-(null)
DR13   -0.66 dB    -17.58 dB       4:15  00-(null)
DR12   -2.21 dB    -18.65 dB       6:52  00-(null)
DR12   -1.69 dB    -16.16 dB       4:15  00-(null)
DR13   -1.33 dB    -18.61 dB       4:12  00-(null)
DR12   -0.36 dB    -17.19 dB       4:13  00-(null)
---------------------------------------------------------------------------------------------------------
Number of tracks:  8
Official DR value: DR13
```

It would be cool to use some grid widget instead of plain text field for readability.

**Comment by dakeryas** [comment]
I guess the filename bit should be easy.
You are correct regarding the text box, I am completely new to GTK and did something that could at least be pasted somewhere else (for http://dr.loudness-war.info), and thanks fot the Grid widget tip!

**Comment by dakeryas** [comment]
I have address your folder and filename suggestions in https://github.com/dakeryas/deadbeef-dr-meter/commit/cc8065c63f9a1e66cb9d86d7d748ce6d9e489944

Please open another ticket for the grid widget with more info.
