### ISSUE TITLE
Request: Infobar Plugin Support For The Latest Deadbeef?

### ISSUE THREAD

**Issue by 0pLuS0** [dakeryas/deadbeef-dr-meter#3]
Hello,

Would you be able to correct the source code in the Infobar Plugin 1.4 to work with the latest versions of Deadbeef?

The reason I am asking you, since you have done coding in Deadbeef for this project, I'm hoping you can do this, if you have the free time.

I posted an issue about this on Deadbeef's Github repo, but unfortunately no one has come forward to update this, which is really a shame.

https://github.com/DeaDBeeF-Player/deadbeef/issues/2206

If you are familiar with the plugin, the reason I want to use it, it also has Biography support besides Lyrics.

You can only use deadbeef-0.7.2 with the Infobar Plugin.

I'm attaching the original source for the Infobar plugin.

Thank you for your time and consideration, please let me know. :)

[deadbeef-infobar_1.4.orig.tar.gz](https://github.com/dakeryas/deadbeef-dr-meter/files/8120857/deadbeef-infobar_1.4.orig.tar.gz)

**Comment by dakeryas** [comment]
Yes that is a shame, but I am unfortunately time-limited at the moment.

**Comment by 0pLuS0** [comment]
No worries deadbeef-infobar-ng has had some recent updates, so it's working at present.

https://github.com/loskutov/deadbeef-infobar-ng/issues

THANKS
